name: "PR change detector"
description: "Detect if path changes"
inputs:
  path:
    description: "paths to detect"
    required: true
    default: "TODO_FILENAME"
outputs:
  changed: # id of output
    description: "whether changed"
runs:
  using: "node12"
  main: "dist/bundle.js"
